remote_theme: just-the-docs/just-the-docs
title: "unicornpkg"
plugins:
  - jekyll-redirect-from
exclude:
  - .obsidian/
  - CNAME
  - .git*
aux_links:
  "Discord":
  - "//discord.gg/Xs3VKNJrMb"
  "GitHub":
    - "//github.com/unicornpkg"
  "Roadmap":
    - "//github.com/orgs/unicornpkg/projects/1"
redirects: true
nav_external_links:
  - title: Reference docs (API and CLI)
    url: "https://unicornpkg.github.io/libunicornpkg"
  - title: Specification
    url: "https://unicornpkg.github.io/spec/"
  - title: Code of Conduct
    url: "https://github.com/unicornpkg/.github/blob/main/CODE_OF_CONDUCT.md"
